// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../test/scripts/webdavtestapp.js', ['webdav.TestApp'], ['goog.Uri', 'goog.debug.Console', 'goog.debug.Logger', 'goog.events', 'goog.net.XhrIo', 'goog.net.XhrManager', 'goog.object', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
