// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/webdavclient.js', ['webdav.Client'], ['goog.Uri', 'goog.net.XhrManager', 'goog.object']);
