// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/config.js', ['xhrdav.lib', 'xhrdav.lib.Config'], ['goog.Disposable', 'goog.debug.Console', 'goog.debug.Logger', 'goog.object', 'goog.string.path', 'xhrdav.lib.HttpStatus', 'xhrdav.lib.string']);
goog.addDependency('../../../scripts/core_ext/string.js', ['xhrdav.lib.string'], ['goog.array', 'goog.functions']);
goog.addDependency('../../../scripts/davclient.js', ['xhrdav.lib.Client'], ['goog.Uri', 'goog.dom', 'goog.net.XhrIo', 'goog.net.XhrManager', 'xhrdav.lib.Config']);
goog.addDependency('../../../scripts/davfs.js', ['xhrdav.lib.DavFs'], ['xhrdav.lib.Client', 'xhrdav.lib.Config']);
goog.addDependency('../../../scripts/domhandler.js', ['xhrdav.lib.DomHandler'], ['xhrdav.lib.Config']);
goog.addDependency('../../../scripts/domparser.js', ['xhrdav.lib.DomParser'], ['goog.dom.xml', 'xhrdav.lib.Config']);
goog.addDependency('../../../scripts/functions/domparse.js', ['xhrdav.lib.functions.DomParse'], ['xhrdav.lib.Config', 'xhrdav.lib.DomHandler', 'xhrdav.lib.DomParser']);
goog.addDependency('../../../scripts/httpstatus.js', ['xhrdav.lib.HttpStatus'], []);
