// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/config.js', ['xhrdav.lib', 'xhrdav.lib.Config'], ['goog.array', 'goog.debug.Console', 'goog.debug.ErrorHandler', 'goog.debug.Logger', 'goog.dom', 'goog.functions', 'goog.json', 'goog.net.XhrIo', 'goog.object', 'goog.string.path', 'xhrdav.lib.Errors', 'xhrdav.lib.HttpStatus', 'xhrdav.lib.string', 'xhrdav.lib.utils']);
goog.addDependency('../../../scripts/core_ext/string.js', ['xhrdav.lib.string'], ['goog.array', 'goog.functions']);
goog.addDependency('../../../scripts/davclient.js', ['xhrdav.lib.Client'], ['goog.Uri', 'goog.dom', 'goog.net.XhrIo', 'xhrdav.lib.Config']);
goog.addDependency('../../../scripts/davfs.js', ['xhrdav.lib.DavFs', 'xhrdav.lib.DavFs.Request'], ['goog.Disposable', 'goog.net.XhrManager', 'xhrdav.lib.Client', 'xhrdav.lib.Config', 'xhrdav.lib.ResourceBuilder', 'xhrdav.lib.ResourceController']);
goog.addDependency('../../../scripts/domhandler.js', ['xhrdav.lib.DomHandler'], []);
goog.addDependency('../../../scripts/domparser.js', ['xhrdav.lib.DomParser'], ['goog.dom.xml', 'goog.functions']);
goog.addDependency('../../../scripts/errors.js', ['xhrdav.lib.Errors'], ['goog.array', 'goog.json', 'goog.object']);
goog.addDependency('../../../scripts/httpstatus.js', ['xhrdav.lib.HttpStatus'], []);
goog.addDependency('../../../scripts/resource.js', ['xhrdav.lib.Resource'], ['goog.array', 'goog.object']);
goog.addDependency('../../../scripts/resourcebuilder.js', ['xhrdav.lib.ResourceBuilder'], ['xhrdav.lib.Config', 'xhrdav.lib.ResourceController']);
goog.addDependency('../../../scripts/resourcecontroller.js', ['xhrdav.lib.ResourceController'], ['xhrdav.lib.Config', 'xhrdav.lib.Resource']);
goog.addDependency('../../../scripts/utils.js', ['xhrdav.lib.utils'], ['xhrdav.lib.utils.domparse', 'xhrdav.lib.utils.path']);
goog.addDependency('../../../scripts/utils/domparse.js', ['xhrdav.lib.utils.domparse'], ['xhrdav.lib.DomHandler', 'xhrdav.lib.DomParser']);
goog.addDependency('../../../scripts/utils/path.js', ['xhrdav.lib.utils.path'], ['goog.array', 'goog.string', 'goog.string.path']);
