// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../src/client.js', ['xhrdav.Client'], ['goog.Uri', 'goog.dom', 'goog.net.XhrIo', 'xhrdav.Conf']);
goog.addDependency('../../../src/conf.js', ['xhrdav.Conf'], ['goog.debug.Console', 'goog.debug.ErrorHandler', 'goog.debug.Logger', 'goog.net.XhrIo', 'xhrdav.lib']);
goog.addDependency('../../../src/davfs.js', ['xhrdav.DavFs', 'xhrdav.DavFs.Request'], ['goog.net.XhrManager', 'xhrdav.Client', 'xhrdav.Conf', 'xhrdav.Errors', 'xhrdav.ResourceBuilder', 'xhrdav.ResourceController']);
goog.addDependency('../../../src/errors.js', ['xhrdav.Errors'], ['goog.array', 'goog.json', 'goog.object']);
goog.addDependency('../../../src/ext.js', ['xhrdav.ext'], ['xhrdav.ext.string']);
goog.addDependency('../../../src/ext/string.js', ['xhrdav.ext.string'], ['goog.array', 'goog.functions']);
goog.addDependency('../../../src/httpstatus.js', ['xhrdav.HttpStatus'], []);
goog.addDependency('../../../src/lib.js', ['xhrdav.lib'], ['goog.array', 'goog.dom', 'goog.functions', 'goog.json', 'goog.object', 'goog.string.path', 'xhrdav.HttpStatus', 'xhrdav.ext', 'xhrdav.utils']);
goog.addDependency('../../../src/parser/domhandler.js', ['xhrdav.parser.DomHandler'], ['goog.Disposable']);
goog.addDependency('../../../src/parser/domparser.js', ['xhrdav.parser.DomParser'], ['goog.dom.xml', 'goog.functions']);
goog.addDependency('../../../src/resource.js', ['xhrdav.Resource'], ['goog.array', 'goog.object']);
goog.addDependency('../../../src/resourcebuilder.js', ['xhrdav.ResourceBuilder'], ['xhrdav.Conf', 'xhrdav.ResourceController']);
goog.addDependency('../../../src/resourcecontroller.js', ['xhrdav.ResourceController'], ['xhrdav.Conf', 'xhrdav.Resource']);
goog.addDependency('../../../src/utils.js', ['xhrdav.utils'], ['xhrdav.utils.domparse', 'xhrdav.utils.path']);
goog.addDependency('../../../src/utils/domparse.js', ['xhrdav.utils.domparse'], ['xhrdav.parser.DomHandler', 'xhrdav.parser.DomParser']);
goog.addDependency('../../../src/utils/path.js', ['xhrdav.utils.path'], ['goog.array', 'goog.string', 'goog.string.path']);
goog.addDependency('../../../src/xhrdav.js', ['xhrdav'], ['xhrdav.Client', 'xhrdav.Conf', 'xhrdav.DavFs', 'xhrdav.Errors', 'xhrdav.HttpStatus', 'xhrdav.Resource', 'xhrdav.ResourceBuilder', 'xhrdav.ResourceController', 'xhrdav.ext', 'xhrdav.lib', 'xhrdav.parser.DomHandler', 'xhrdav.parser.DomParser', 'xhrdav.utils']);
